spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

app:
  cookie:
    secure: true
    same-site: Strict

server:
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    root: WARN
    com.example.application: INFO
